/* Generated by reswrap from file adie_gif.gif */
extern const unsigned char adie_gif[];

/* Generated by reswrap from file big_gif.gif */
extern const unsigned char big_gif[];

/* Generated by reswrap from file bookset_gif.gif */
extern const unsigned char bookset_gif[];

/* Generated by reswrap from file booknext_gif.gif */
extern const unsigned char booknext_gif[];

/* Generated by reswrap from file bookprev_gif.gif */
extern const unsigned char bookprev_gif[];

/* Generated by reswrap from file bookdel_gif.gif */
extern const unsigned char bookdel_gif[];

/* Generated by reswrap from file close_gif.gif */
extern const unsigned char close_gif[];

/* Generated by reswrap from file colors_gif.gif */
extern const unsigned char colors_gif[];

/* Generated by reswrap from file copy_gif.gif */
extern const unsigned char copy_gif[];

/* Generated by reswrap from file cut_gif.gif */
extern const unsigned char cut_gif[];

/* Generated by reswrap from file delete_gif.gif */
extern const unsigned char delete_gif[];

/* Generated by reswrap from file fonts_gif.gif */
extern const unsigned char fonts_gif[];

/* Generated by reswrap from file help_gif.gif */
extern const unsigned char help_gif[];

/* Generated by reswrap from file indent_gif.gif */
extern const unsigned char indent_gif[];

/* Generated by reswrap from file info_gif.gif */
extern const unsigned char info_gif[];

/* Generated by reswrap from file lang_gif.gif */
extern const unsigned char lang_gif[];

/* Generated by reswrap from file new_gif.gif */
extern const unsigned char new_gif[];

/* Generated by reswrap from file open_gif.gif */
extern const unsigned char open_gif[];

/* Generated by reswrap from file palette_gif.gif */
extern const unsigned char palette_gif[];

/* Generated by reswrap from file pattern_gif.gif */
extern const unsigned char pattern_gif[];

/* Generated by reswrap from file paste_gif.gif */
extern const unsigned char paste_gif[];

/* Generated by reswrap from file print_gif.gif */
extern const unsigned char print_gif[];

/* Generated by reswrap from file quit_gif.gif */
extern const unsigned char quit_gif[];

/* Generated by reswrap from file redo_gif.gif */
extern const unsigned char redo_gif[];

/* Generated by reswrap from file reload_gif.gif */
extern const unsigned char reload_gif[];

/* Generated by reswrap from file save_gif.gif */
extern const unsigned char save_gif[];

/* Generated by reswrap from file saveas_gif.gif */
extern const unsigned char saveas_gif[];

/* Generated by reswrap from file search_gif.gif */
extern const unsigned char search_gif[];

/* Generated by reswrap from file searchnext_gif.gif */
extern const unsigned char searchnext_gif[];

/* Generated by reswrap from file searchprev_gif.gif */
extern const unsigned char searchprev_gif[];

/* Generated by reswrap from file shiftleft_gif.gif */
extern const unsigned char shiftleft_gif[];

/* Generated by reswrap from file shiftright_gif.gif */
extern const unsigned char shiftright_gif[];

/* Generated by reswrap from file styles_gif.gif */
extern const unsigned char styles_gif[];

/* Generated by reswrap from file small_gif.gif */
extern const unsigned char small_gif[];

/* Generated by reswrap from file syntax_gif.gif */
extern const unsigned char syntax_gif[];

/* Generated by reswrap from file undo_gif.gif */
extern const unsigned char undo_gif[];

