##############################################################################
#                                                                            #
#                       FOX:  A Free C++ Class Library for X                 #
#                                                                            #
##############################################################################
# Copyright (C) 1997,2005 by Jeroen van der Zijp.   All Rights Reserved.     #
##############################################################################
# $Id: Makefile.wc,v 1.8.2.1 2005/02/10 23:44:42 fox Exp $                       #
##############################################################################
# This library is free software; you can redistribute it and/or              #
# modify it under the terms of the GNU Library General Public                #
# License as published by the Free Software Foundation; either               #
# version 2 of the License, or (at your option) any later version.           #
#                                                                            #
# This library is distributed in the hope that it will be useful,            #
# but WITHOUT ANY WARRANTY; without even the implied warranty of             #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU          #
# Library General Public License for more details.                           #
#                                                                            #
# You should have received a copy of the GNU Library General Public          #
# License along with this library; if not, write to the Free                 #
# Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.         #
##############################################################################

# For use with OpenWatcom C++ v1.0 or later
CXX       = wpp386
CXXFLAGS  = /w3 /zq /5r /ei /fp5 /oneatlx /zp=4
RM        = del
TOPDIR    = ..
DEFINES   = -DNDEBUG -DFOX_BIGENDIAN=0 -DWIN32 -D_WINDOWS -DHAVE_GL_H -DHAVE_GLU_H #-DHAVE_PNG_H -DHAVE_JPEG_H -DHAVE_TIFF_H -DXMD_H
LD	  = wcl386
LDFLAGS   = -l=nt_win
GLLIBS    = opengl32.lib glu32.lib
INCDIRS   = -I$(TOPDIR)\include
FOXLIB    = $(TOPDIR)\src\FOX-1.4.lib $(%WATCOM)\lib386\nt\comctl32.lib $(%WATCOM)\lib386\nt\wsock32.lib

PROGRAMS  =
PROGRAMS += rex.exe
PROGRAMS += minheritance.exe
PROGRAMS += memmap.exe
PROGRAMS += mditest.exe
PROGRAMS += table.exe
PROGRAMS += groupbox.exe
PROGRAMS += foursplit.exe
PROGRAMS += datatarget.exe
PROGRAMS += scribble.exe
PROGRAMS += splitter.exe
PROGRAMS += shutter.exe
PROGRAMS += image.exe
PROGRAMS += header.exe
PROGRAMS += hello.exe
PROGRAMS += hello2.exe
PROGRAMS += switcher.exe
PROGRAMS += iconlist.exe
PROGRAMS += tabbook.exe
PROGRAMS += dialog.exe
PROGRAMS += dirlist.exe
PROGRAMS += button.exe
PROGRAMS += dctest.exe
PROGRAMS += glviewer.exe
PROGRAMS += gltest.exe
PROGRAMS += wizard.exe
PROGRAMS += imageviewer.exe

.cpp.obj: .AUTODEPEND
	$(CXX) $(INCDIRS) $(CXXFLAGS) $(DEFINES) $*.cpp

all: $(PROGRAMS)

rex.exe: $(FOXLIB) rex.obj
	$(LD) rex.obj $(FOXLIB)			# note: create console app

minheritance.exe: $(FOXLIB) minheritance.obj
	$(LD) minheritance.obj $(FOXLIB)	# note: create console app

memmap.exe: $(FOXLIB) memmap.obj
	$(LD) memmap.obj $(FOXLIB)	# note: create console app

wizard.exe: $(FOXLIB) wizard.obj
	$(LD) $(LDFLAGS) wizard.obj $(FOXLIB)

foursplit.exe: $(FOXLIB) foursplit.obj
	$(LD) $(LDFLAGS) foursplit.obj $(FOXLIB)

tabbook.exe: $(FOXLIB) tabbook.obj
	$(LD) $(LDFLAGS) tabbook.obj $(FOXLIB)

table.exe: $(FOXLIB) table.obj
	$(LD) $(LDFLAGS) table.obj $(FOXLIB)

switcher.exe: $(FOXLIB) switcher.obj
	$(LD) $(LDFLAGS) switcher.obj $(FOXLIB)

button.exe: $(FOXLIB) button.obj
	$(LD) $(LDFLAGS) button.obj $(FOXLIB)

mditest.exe: $(FOXLIB) mditest.obj
	$(LD) $(LDFLAGS) mditest.obj $(FOXLIB)

datatarget.exe: $(FOXLIB) datatarget.obj
	$(LD) $(LDFLAGS) datatarget.obj $(FOXLIB)

imageviewer.exe: $(FOXLIB) imageviewer.obj
	$(LD) $(LDFLAGS) imageviewer.obj $(FOXLIB) #libpng.lib zlib.lib libjpeg.lib libtiff.lib

hello.exe: $(FOXLIB) hello.obj
	$(LD) $(LDFLAGS) hello.obj $(FOXLIB)

hello2.exe: $(FOXLIB) hello2.obj
	$(LD) $(LDFLAGS) hello2.obj $(FOXLIB)

dirlist.exe: $(FOXLIB) dirlist.obj
	$(LD) $(LDFLAGS) dirlist.obj $(FOXLIB)

groupbox.exe: $(FOXLIB) groupbox.obj
	$(LD) $(LDFLAGS) groupbox.obj $(FOXLIB)

scribble.exe: $(FOXLIB) scribble.obj
	$(LD) $(LDFLAGS) scribble.obj $(FOXLIB)

splitter.exe: $(FOXLIB) splitter.obj
	$(LD) $(LDFLAGS) splitter.obj $(FOXLIB)

iconlist.exe: $(FOXLIB) iconlist.obj
	$(LD) $(LDFLAGS) iconlist.obj $(FOXLIB)

header.exe: $(FOXLIB) header.obj
	$(LD) $(LDFLAGS) header.obj $(FOXLIB)

shutter.exe: $(FOXLIB) shutter.obj
	$(LD) $(LDFLAGS) shutter.obj $(FOXLIB)

image.exe: $(FOXLIB) image.obj
	$(LD) $(LDFLAGS) image.obj $(FOXLIB)

gltest.exe: $(FOXLIB) gltest.obj
	$(LD) $(LDFLAGS) gltest.obj $(FOXLIB) $(GLLIBS)

glviewer.exe: $(FOXLIB) glviewer.obj
	$(LD) $(LDFLAGS) glviewer.obj $(FOXLIB) $(GLLIBS)

dialog.exe: $(FOXLIB) dialog.obj
	$(LD) $(LDFLAGS) dialog.obj $(FOXLIB)

dctest.exe: $(FOXLIB) dctest.obj
	$(LD) $(LDFLAGS) dctest.obj $(FOXLIB)

clean: .SYMBOLIC
	del *.obj
	del *.exe
	del *.tds
