##############################################################################
#                                                                            #
#                       FOX:  A Free C++ Class Library for X                 #
#                                                                            #
##############################################################################
# Copyright (C) 1997 by Jeroen van der Zijp.   All Rights Reserved.          #
##############################################################################
# $Id: Makefile.nt,v 1.1 1998/09/29 20:16:43 jeroen Exp $                   #
##############################################################################
# This library is free software; you can redistribute it and/or              #
# modify it under the terms of the GNU Library General Public                #
# License as published by the Free Software Foundation; either               #
# version 2 of the License, or (at your option) any later version.           #
#                                                                            #
# This library is distributed in the hope that it will be useful,            #
# but WITHOUT ANY WARRANTY; without even the implied warranty of             #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU          #
# Library General Public License for more details.                           #
#                                                                            #
# You should have received a copy of the GNU Library General Public          #
# License along with this library; if not, write to the Free                 #
# Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.         #
##############################################################################


CC        = cl
LD        = link
LDOUT     = /out:
FLGS      = /MLd /W1 /GX /Z7 /Od
CLSTAB    = ../utils/clstab
CFLAGS    = $(FLGS) /Tp
DEFINES   = -DHAVE_OPENGL -DHUMMINGBIRD -DWIN32
INCDIRS   = -I../include -I/exceed.nt/xdk/include
LIBS      = libcd.lib kernel32.lib user32.lib gdi32.lib wsock32.lib winspool.lib hclglx.lib hclglu.lib xlibgui.lib xlib.lib oldnames.lib xt.lib xmu.lib
FOXLIB    = ../lib/fox.lib

.SUFFIXES: .cc .c


PROGRAMS  = datatarget.exe dirlist.exe mditest.exe textedit.exe groupbox.exe glviewer.exe\
            iconlist.exe window.exe scribble.exe splitter.exe \
            shutter.exe image.exe gltest.exe header.exe hello.exe hello2.exe dialog.exe

SOURCES = window.cc mditest.cc groupbox.cc scribble.cc splitter.cc header.cc textedit.cc \
          iconlist.cc gltest.cc shutter.cc glviewer.cc image.cc hello.cc hello2.cc dirlist.cc\
	  datatarget.cc dialog.cc


OBJECTS = $(SOURCES:.cc=.obj)

%.obj: %.cc
	$(CC) /c $(INCDIRS) $(DEFINES) $(CFLAGS) $*.cc

all: $(PROGRAMS)

mditest.exe: $(FOXLIB) mditest.obj
	link /out:$@ $(LDFLAGS) $(LIBDIRS) mditest.obj ../lib/fox.lib $(LIBS)

datatarget.exe: $(FOXLIB) datatarget.obj
	link /out:$@ $(LDFLAGS) $(LIBDIRS) datatarget.obj ../lib/fox.lib $(LIBS)

window.exe: $(FOXLIB) window.obj
	link /out:$@ $(LDFLAGS) $(LIBDIRS) window.obj -lFOX -lm ../lib/fox.lib $(LIBS)

hello.exe: $(FOXLIB) hello.obj
	link /out:$@ $(LDFLAGS) $(LIBDIRS) hello.obj ../lib/fox.lib $(LIBS)

hello2.exe: $(FOXLIB) hello2.obj
	link /out:$@ $(LDFLAGS) $(LIBDIRS) hello2.obj ../lib/fox.lib $(LIBS)

dirlist.exe: $(FOXLIB) dirlist.obj
	link /out:$@ $(LDFLAGS) $(LIBDIRS) dirlist.obj ../lib/fox.lib $(LIBS)

groupbox.exe: $(FOXLIB) groupbox.obj
	link /out:$@ $(LDFLAGS) $(LIBDIRS) groupbox.obj ../lib/fox.lib $(LIBS)

scribble.exe: $(FOXLIB) scribble.obj
	link /out:$@ $(LDFLAGS) $(LIBDIRS) scribble.obj ../lib/fox.lib $(LIBS) 

splitter.exe: $(FOXLIB) splitter.obj
	link /out:$@ $(LDFLAGS) $(LIBDIRS) splitter.obj ../lib/fox.lib $(LIBS) 

iconlist.exe: $(FOXLIB) iconlist.obj
	link /out:$@ $(LDFLAGS) $(LIBDIRS) iconlist.obj ../lib/fox.lib $(LIBS)

header.exe: $(FOXLIB) header.obj
	link /out:$@ $(LDFLAGS) $(LIBDIRS) header.obj ../lib/fox.lib $(LIBS)

shutter.exe: $(FOXLIB) shutter.obj
	link /out:$@ $(LDFLAGS) $(LIBDIRS) shutter.obj ../lib/fox.lib $(LIBS)

image.exe: $(FOXLIB) image.obj
	link /out:$@ $(LDFLAGS) $(LIBDIRS) image.obj ../lib/fox.lib $(LIBS)

textedit.exe: $(FOXLIB) textedit.obj
	link /out:$@ $(LDFLAGS) $(LIBDIRS) textedit.obj ../lib/fox.lib $(LIBS)

gltest.exe: $(FOXLIB) gltest.obj
	link /out:$@ $(LDFLAGS) $(LIBDIRS) gltest.obj ../lib/fox.lib $(LIBS)

glviewer.exe: $(FOXLIB) glviewer.obj
	link /out:$@ $(LDFLAGS) $(LIBDIRS) glviewer.obj ../lib/fox.lib $(LIBS)

dialog.exe: $(FOXLIB) dialog.obj
	link /out:$@ $(LDFLAGS) $(LIBDIRS) dialog.obj ../lib/fox.lib $(LIBS)
        
clean:
	$(RM) *.obj *~

realclean: clean
	$(RM) $(PROGRAMS)
	$(RM) Makefile

dep: $(SOURCES)
	gcc -I../include -MM $(SOURCES) >depend

include depend
