/* Generated by reswrap from file colors.gif */
extern const unsigned char colors[];

/* Generated by reswrap from file information.gif */
extern const unsigned char information[];

/* Generated by reswrap from file bigcalc.gif */
extern const unsigned char bigcalc[];

/* Generated by reswrap from file constmem.bmp */
extern const unsigned char constmem[];

/* Generated by reswrap from file question.gif */
extern const unsigned char question[];

/* Generated by reswrap from file tinycalc.gif */
extern const unsigned char tinycalc[];

