.TH reswrap 1 "July 1999" "The FOX C++ GUI Toolkit" "FOX Programmers Manual"

.SH NAME
reswrap \- wrap icon resources into C code

.SH SYNOPSIS
.B reswrap
.RB [ \-o [ a "] "
.IR outfile ]
.RB [ \-h "] [" \-v "] [" \-d "] [" \-x "] [" \-e "] [" \-i "] [" \-s ]
.RB [ \-n
.IR name ]
.RB [ \-c
.IR cols ]
.RB [ \-ppm ]
.I files

.SH DESCRIPTION
The
.B reswrap
tool is used to turn images and other resource files into embeddable C or C++ data arrays.
The output file can then be easily compiled into the application.
By default reswrap will interpret the
.I files
listed as a stream of raw bytes and output them as an initialized data array on stdout, ready
to be compiled into the application.

.SH OPTIONS
.TP
\fB\-o\fR[\fBa\fR]\fI outfile\fR
Write the result into the file
.I outfile
instead of writing to stdout. With
\fB\-o\fR
the
.I outfile
will be overwritten with the data from the input.
With the
\fB\-oa\fR
option, the resulting code is appended to the
.I output
file, allowing multiple input files to be placed into one single resource source file.

.TP
\fB\-h\fR
Print a short usage message.

.TP
\fB\-v\fR
Just print out the version number and terminate.

.TP
\fB\-d\fR
Write data as decimal numbers instead of using the default hexadecimal numbers.

.TP
\fB\-x\fR
Write data as hexadecimal numbers (default).

.TP
\fB\-e\fR
Places the storage modifier extern in front of the data array, ensuring
that the data array can be linked with other compilation units.

.TP
\fB\-i\fR
Instead of generating an array definition only write a declaration, which
can be included as a header file.

.TP
\fB\-s\fR
This option suppresses comments inserted by reswrap to indicate the
original file name from which the data statement was generated.

.TP
\fB\-n\fI name\fR
Instead of taking the filename less the extension, reswrap substitutes
.I name
for the name of the resource.

.TP
\fB\-c\fI cols\fR
Writes
.I cols
columns instead of the default 16 columns in the data statements
generated by reswrap.

.TP
\fB\-ppm\fR
Assumes the source file is a Portable Pixmap (ppm) file.  Reswrap will
output a simple rgb array.

.SH SEE ALSO
The reswrap program is a part of the FOX GUI Toolkit.  The FOX Toolkit may be found at

.B http://www.fox-toolkit.org

The FOX website has the official FOX documentation in HTML which includes
some additional information about reswrap and its use.
If you installed the libfox0.99-doc package you can find this in

.B /usr/share/doc/libfox0.99/html/fox.html

also.

.SH AUTHOR
This manpage was originally written by Torsten Landschoff (torsten@debian.org)
for the Debian distribution of the FOX Toolkit.

The main author of FOX is Jeroen van der Zijp <jeroen@fox-toolkit.org>. For a list of
contributors see /usr/share/doc/libfox0.99/AUTHORS.

