/* Generated by reswrap from file bigicons.bmp */
extern const unsigned char bigicons[];

/* Generated by reswrap from file bigpenguin.bmp */
extern const unsigned char bigpenguin[];

/* Generated by reswrap from file clrbook.gif */
extern const unsigned char clrbook[];

/* Generated by reswrap from file copy.bmp */
extern const unsigned char copy[];

/* Generated by reswrap from file copyit.gif */
extern const unsigned char copyit[];

/* Generated by reswrap from file cut.bmp */
extern const unsigned char cut[];

/* Generated by reswrap from file deleteit.bmp */
extern const unsigned char deleteit[];

/* Generated by reswrap from file desktop.bmp */
extern const unsigned char desktop[];

/* Generated by reswrap from file details.bmp */
extern const unsigned char details[];

/* Generated by reswrap from file dirup.bmp */
extern const unsigned char dirup[];

/* Generated by reswrap from file goback.bmp */
extern const unsigned char goback[];

/* Generated by reswrap from file goforw.bmp */
extern const unsigned char goforw[];

/* Generated by reswrap from file gotodir.bmp */
extern const unsigned char gotodir[];

/* Generated by reswrap from file home.gif */
extern const unsigned char home[];

/* Generated by reswrap from file hosts.bmp */
extern const unsigned char hosts[];

/* Generated by reswrap from file linkit.gif */
extern const unsigned char linkit[];

/* Generated by reswrap from file maphost.bmp */
extern const unsigned char maphost[];

/* Generated by reswrap from file moveit.gif */
extern const unsigned char moveit[];

/* Generated by reswrap from file minipenguin.bmp */
extern const unsigned char minipenguin[];

/* Generated by reswrap from file paste.bmp */
extern const unsigned char paste[];

/* Generated by reswrap from file properties.bmp */
extern const unsigned char properties[];

/* Generated by reswrap from file setbook.gif */
extern const unsigned char setbook[];

/* Generated by reswrap from file smallicons.bmp */
extern const unsigned char smallicons[];

/* Generated by reswrap from file unmaphost.bmp */
extern const unsigned char unmaphost[];

/* Generated by reswrap from file work.gif */
extern const unsigned char work[];

